// utils/downloadPdf.js
import jsPDF from "jspdf";
import "jspdf-autotable";

export const downloadPdf = (aiResponse, fileName, formData = {}) => {
  const doc = new jsPDF({
    unit: "pt",
    format: "a4",
  });

  const margin = 40;
  const lineHeight = 18;
  const pageWidth = doc.internal.pageSize.getWidth();

  // === Header ===
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(3, 99, 77);
  doc.text("AI Marketing Plan", margin, 60);

  // === Business Info Box ===
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(40, 40, 40);

  const infoY = 90;
  const info = [
    ["Business Name:", formData.businessName || "—"],
    ["Business Type:", formData.businessType || "—"],
    ["Target Audience:", formData.targetAudience || "—"],
    ["Budget:", formData.budget || "—"],
    ["Goals:", formData.goals || "—"],
  ];

  let infoX = margin;
  info.forEach(([label, value], idx) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, infoX, infoY + idx * lineHeight);
    doc.setFont("helvetica", "normal");
    doc.text(value, infoX + 130, infoY + idx * lineHeight);
  });

  // === Divider line ===
  doc.setDrawColor(200);
  doc.line(margin, infoY + info.length * lineHeight + 10, pageWidth - margin, infoY + info.length * lineHeight + 10);

  // === AI Plan ===
  let yPos = infoY + info.length * lineHeight + 40;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Step-by-Step Marketing Plan:", margin, yPos);
  yPos += 25;

  const steps = aiResponse.split(/\n(?=\d+\.)/).filter((s) => s.trim() !== "");

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);

  steps.forEach((step, i) => {
    const text = doc.splitTextToSize(step.trim(), pageWidth - margin * 2);
    if (yPos + text.length * lineHeight > doc.internal.pageSize.height - 80) {
      doc.addPage();
      yPos = 60;
    }
    doc.text(text, margin, yPos);
    yPos += text.length * lineHeight + 10;
  });

  // === Footer ===
  const date = new Date().toLocaleDateString();
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated by AI Marketing Planner on ${date}`,
    margin,
    doc.internal.pageSize.height - 40
  );

  doc.save(fileName);
};
