// utils/downloadPdf.js
import jsPDF from "jspdf";
import "jspdf-autotable";

export const downloadPdf = (aiResponse, fileName, formData = {}) => {
  const doc = new jsPDF({
    unit: "pt",
    format: "a4",
    compress: true,
  });

  const margin = 40;
  const lineHeight = 18;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // === Header ===
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(3, 99, 77);
  doc.text("AI Marketing Plan", margin, 60);

  // === Business Info Box ===
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(40, 40, 40);

  const infoY = 90;
  const info = [
    ["Business Name:", formData.businessName || "—"],
    ["Business Type:", formData.businessType || "—"],
    ["Target Audience:", formData.targetAudience || "—"],
    ["Budget:", formData.budget || "—"],
    ["Goals:", formData.goals || "—"],
  ];

  info.forEach(([label, value], idx) => {
    const y = infoY + idx * lineHeight;
    doc.setFont("helvetica", "bold");
    doc.text(label, margin, y);
    doc.setFont("helvetica", "normal");
    // Prevent overflow text
    const wrappedValue = doc.splitTextToSize(value, pageWidth - margin * 2 - 130);
    doc.text(wrappedValue, margin + 130, y);
  });

  // === Divider line ===
  const dividerY = infoY + info.length * lineHeight + 10;
  doc.setDrawColor(200);
  doc.line(margin, dividerY, pageWidth - margin, dividerY);

  // === AI Plan ===
  let yPos = dividerY + 40;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Step-by-Step Marketing Plan:", margin, yPos);
  yPos += 25;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.setTextColor(60, 60, 60);

  // Split AI response into readable steps
  const steps = aiResponse
    ? aiResponse.split(/\n(?=\d+\.)/).filter((s) => s.trim() !== "")
    : ["No marketing plan generated."];

  steps.forEach((step) => {
    const text = doc.splitTextToSize(step.trim(), pageWidth - margin * 2);
    // Page overflow control
    if (yPos + text.length * lineHeight > pageHeight - 80) {
      doc.addPage();
      yPos = 60;
    }
    doc.text(text, margin, yPos);
    yPos += text.length * lineHeight + 10;
  });

  // === Footer ===
  const date = new Date().toLocaleDateString();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated by AI Marketing Planner on ${date}`,
    margin,
    doc.internal.pageSize.getHeight() - 40
  );

  // === Save PDF ===
  doc.save(fileName || "MarketingPlan.pdf");
};
