// src/utils/downloadPdf.js
import jsPDF from "jspdf";
import "jspdf-autotable";

export const downloadPdf = (aiResponse, fileName, formData = {}) => {
  const doc = new jsPDF({
    unit: "pt",
    format: "a4",
    compress: true,
  });

  const margin = 40;
  const lineHeight = 18;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Safe normalization function (same logic as frontend)
  const normalize = (text = "") =>
    String(text)
      .replace(/[‘’]/g, "'")
      .replace(/[“”]/g, '"')
      .replace(/—/g, "-")
      .replace(/\u00A0/g, " ")
      .replace(/\r\n/g, "\n")
      .replace(/\r/g, "\n")
      .replace(/\n{3,}/g, "\n\n")
      .trim();

  const cleaned = normalize(aiResponse);

  // Header
  doc.setFont("times", "bold");
  doc.setFontSize(20);
  doc.setTextColor(3, 99, 77);
  doc.text("AI Marketing Plan", margin, 60);

  // Business info block
  doc.setFont("times", "normal");
  doc.setFontSize(11);
  const infoY = 90;
  const lineGap = lineHeight;
  const info = [
    ["Business Name:", formData.businessName || "—"],
    ["Business Type:", formData.businessType || "—"],
    ["Target Audience:", formData.targetAudience || "—"],
    ["Budget:", formData.budget || "—"],
    ["Goals:", formData.goals || "—"],
  ];

  info.forEach(([label, value], idx) => {
    const y = infoY + idx * lineGap;
    doc.setFont("times", "bold");
    doc.text(label, margin, y);
    doc.setFont("times", "normal");
    // wrap the value text if long
    const wrapped = doc.splitTextToSize(String(value), pageWidth - margin * 2 - 130);
    doc.text(wrapped, margin + 130, y);
  });

  const dividerY = infoY + info.length * lineGap + 10;
  doc.setDrawColor(200);
  doc.line(margin, dividerY, pageWidth - margin, dividerY);

  // Steps area
  let yPos = dividerY + 40;
  doc.setFont("times", "bold");
  doc.setFontSize(14);
  doc.text("Step-by-Step Marketing Plan:", margin, yPos);
  yPos += 25;

  doc.setFont("times", "normal");
  doc.setFontSize(12);
  doc.setTextColor(60, 60, 60);

  // If cleaned text is numbered, split; else wrap whole text
  const steps = cleaned
    ? cleaned.split(/\n(?=\d+\.)/).map(s => s.trim()).filter(Boolean)
    : ["No marketing plan generated."];

  steps.forEach((step) => {
    // ensure step is plain text and wrap it to page width
    const stepWrapped = doc.splitTextToSize(step, pageWidth - margin * 2);
    // page break control
    if (yPos + stepWrapped.length * lineHeight > pageHeight - 80) {
      doc.addPage();
      yPos = 60;
    }
    doc.text(stepWrapped, margin, yPos);
    yPos += stepWrapped.length * lineHeight + 10;
  });

  // Footer
  const date = new Date().toLocaleDateString();
  doc.setFont("times", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated by AI Marketing Planner on ${date}`, margin, pageHeight - 40);

  doc.save(fileName || "MarketingPlan.pdf");
};
